# Generated by Django 5.0.7 on 2024-08-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='difficulty',
        ),
    ]
